### ISSUE TITLE
0.08 layer height setting actually has a layer_height of 0.07

### ISSUE THREAD

**Issue by sprior** [Garr-R/MakerGear-PrusaSlicer-Profiles#1]
0.08 layer height setting actually has a layer_height of 0.07

**Comment by sprior** [comment]
The 0.40 mm layer height setting actually has a layer_height of 0.35
The 0.45 mm layer height setting actually has a layer_height of 0.35

**Comment by Garr-Garr** [comment]
Thank you for the report! 

The layer height settings in these experimental profiles are now fixed in the latest version 0.1.1

> https://github.com/Garr-R/MakerGear-PrusaSlicer-Profiles/releases/tag/v0.1.1
