### ISSUE TITLE
Max filament volumetric speeds overridden with same value?

### ISSUE THREAD

**Issue by sprior** [Garr-R/MakerGear-PrusaSlicer-Profiles#2]
filament:*ABS* sets the filament_max_volumetric_speed = 11
filament:MakerGear ABS @MAKERGEAR then overrides it with the same setting

**Comment by Garr-Garr** [comment]
Thank you for the report! 

This duplicate profile setting is now fixed in the latest version 0.1.1

> https://github.com/Garr-R/MakerGear-PrusaSlicer-Profiles/releases/tag/v0.1.1
