### ISSUE TITLE
Consider making the generic filament type profiles available and brand specific optional

### ISSUE THREAD

**Issue by sprior** [Garr-R/MakerGear-PrusaSlicer-Profiles#3]
While I really do appreciate the extreme detail of the brand specific filament profiles for each filament type, I use the same PrusaSlicer (actually the SuperSlicer fork of it) for 5 different printers so having all those printer/brand/filament specific items gets to be a lot.  Since most of them appear to not override any settings besides cost and density which for some might not be critical settings, I'd suggest maybe making the intermediate settings visible so the brand specific settings can be optional.  Most of the time you'd be able to get away with "PETG for MakerGear M2" rather than "Hatchbox PETG for MakerGear".  And you probably weren't going to keep updating the profiles with up to date pricing info anyway though I understand that relative costs might still be a useful reference for some.

**Comment by Garr-Garr** [comment]
Hi @sprior,

The generic filament profiles are in fact available to import from the Configuration Wizard's "Filament" menu:
![image](https://user-images.githubusercontent.com/52166834/172915373-ed0ac347-a5b5-4e00-8eec-0182b9cff842.png)


Unfortunately, I'm not going to delete the brand-specific filament profiles as they're optional and [Prusa](https://github.com/prusa3d/PrusaSlicer/blob/5d82c1601b8897b9113e428bf6b36eaaabd2a101/resources/profiles/PrusaResearch.ini#L2102) /  [other manufacturers](https://github.com/prusa3d/PrusaSlicer/blob/5d82c1601b8897b9113e428bf6b36eaaabd2a101/resources/profiles/Creality.ini#L658) create their vendor profiles this way.

**Comment by sprior** [comment]
That's not actually what I meant.  For example you have a filament:*ABS* which is different from Generic ABS in that it has settings which are specific to MakerGear, but it isn't visible in the GUI.  A user can't choose to just use that and forgo the brand specific settings which only really add a tweak to the density and cost fields.
