### ISSUE TITLE
M3 ID single mode print

### ISSUE THREAD

**Issue by alsted** [Garr-R/MakerGear-PrusaSlicer-Profiles#4]
How is the "empty filament" important for single mode print?

**Comment by Garr-Garr** [comment]
Sorry for the delay here ~ The "empty" filament selection determines which starting script the GCode file will use. For example, if you select the empty filament for Tool_1 the GCode file will use the "Single mode - Tool_0" starting script. If you have filament selected for both hotends the GCode file will use the "Dual Mode" starting script.
